import {
  allConsensusAnswersIn,
  allConsensusReady,
  applyConsensusLobbyPodium,
  buildConsensusDeck,
  buildConsensusReplaySession,
  buildConsensusStandings,
  clampConsensusValue,
  commitConsensusAnswer,
  commitConsensusPlay,
  createStartedConsensusSession,
  defaultConsensusPrepSession,
  formatConsensusScore,
  getConsensusEntryScreen,
  getConsensusModeId,
  getConsensusModes,
  getConsensusPodiumAwards,
  getConsensusPrepSummary,
  getConsensusQuestionCount,
  getConsensusQuestionCountPresets,
  getConsensusSession,
  getConsensusWaitingPlayers,
  isLocalConsensusHost,
  markConsensusLobbyStarted,
  scoreConsensusRound,
  setConsensusMode,
  setConsensusQuestionCount,
  setConsensusReady,
  simulateConsensusReady,
  startConsensusQuestion,
  toggleLocalConsensusReady,
  validateConsensusLaunchConfig,
} from "./consensusSession.js";

export function useConsensusGame() {
  return {
    getSession: getConsensusSession,
    getModes: getConsensusModes,
    getModeId: getConsensusModeId,
    getQuestionCount: getConsensusQuestionCount,
    getQuestionCountPresets: getConsensusQuestionCountPresets,
    getPrepSummary: getConsensusPrepSummary,
    validateLaunchConfig: validateConsensusLaunchConfig,
    getEntryScreen: getConsensusEntryScreen,
    getWaitingPlayers: getConsensusWaitingPlayers,
    buildDeck: buildConsensusDeck,
    buildReplaySession: buildConsensusReplaySession,
    createStartedSession: createStartedConsensusSession,
    buildStandings: buildConsensusStandings,
    getPodiumAwards: getConsensusPodiumAwards,
    scoreRound: scoreConsensusRound,
    applyLobbyPodium: applyConsensusLobbyPodium,
    isHost: isLocalConsensusHost,
    allReady: allConsensusReady,
    allAnswersIn: allConsensusAnswersIn,
    setMode: setConsensusMode,
    setQuestionCount: setConsensusQuestionCount,
    setReady: setConsensusReady,
    toggleLocalReady: toggleLocalConsensusReady,
    simulateReady: simulateConsensusReady,
    startLobbyGame: markConsensusLobbyStarted,
    startQuestion: startConsensusQuestion,
    commitPlay: commitConsensusPlay,
    commitAnswer: commitConsensusAnswer,
    clampValue: clampConsensusValue,
    formatScore: formatConsensusScore,
    defaultSession: defaultConsensusPrepSession,
  };
}
