import {
  allTriviaAnswersIn,
  allTriviaReady,
  countTriviaAnswersIn,
  applyTriviaLobbyPodium,
  buildTriviaDeck,
  buildTriviaReplaySession,
  buildTriviaStandings,
  commitTriviaAnswer,
  commitTriviaPlay,
  createStartedTriviaSession,
  defaultTriviaPrepSession,
  getTriviaEntryScreen,
  getTriviaPodiumAwards,
  getTriviaPrepSummary,
  getTriviaQuestionCount,
  getTriviaQuestionCountPresets,
  getTriviaSession,
  getTriviaThemes,
  getTriviaWaitingPlayers,
  isLocalTriviaHost,
  markTriviaLobbyStarted,
  scoreTriviaRound,
  setTriviaQuestionCount,
  setTriviaReady,
  setTriviaTheme,
  simulateTriviaReady,
  startTriviaQuestion,
  toggleLocalTriviaReady,
  validateTriviaLaunchConfig,
} from "./triviaSession.js";

export function useTriviaGame() {
  return {
    getSession: getTriviaSession,
    getThemes: getTriviaThemes,
    getQuestionCount: getTriviaQuestionCount,
    getQuestionCountPresets: getTriviaQuestionCountPresets,
    getPrepSummary: getTriviaPrepSummary,
    validateLaunchConfig: validateTriviaLaunchConfig,
    getEntryScreen: getTriviaEntryScreen,
    getWaitingPlayers: getTriviaWaitingPlayers,
    buildDeck: buildTriviaDeck,
    buildReplaySession: buildTriviaReplaySession,
    createStartedSession: createStartedTriviaSession,
    buildStandings: buildTriviaStandings,
    getPodiumAwards: getTriviaPodiumAwards,
    scoreRound: scoreTriviaRound,
    applyLobbyPodium: applyTriviaLobbyPodium,
    isHost: isLocalTriviaHost,
    allReady: allTriviaReady,
    allAnswersIn: allTriviaAnswersIn,
    countAnswersIn: countTriviaAnswersIn,
    setTheme: setTriviaTheme,
    setQuestionCount: setTriviaQuestionCount,
    setReady: setTriviaReady,
    toggleLocalReady: toggleLocalTriviaReady,
    simulateReady: simulateTriviaReady,
    startLobbyGame: markTriviaLobbyStarted,
    startQuestion: startTriviaQuestion,
    commitPlay: commitTriviaPlay,
    commitAnswer: commitTriviaAnswer,
    defaultSession: defaultTriviaPrepSession,
  };
}
