/** FEATURE-PROFILE-04 — Carnet Signature (page Profil, pas un onglet). */
export const CARNET_SCREEN_ID = "carnet";

export const CARNET_LABEL = {
  entrySettings: "Mon carnet",
  pageTitle: "Mon carnet",
  lockedTitle: "Carnet Signature",
  lockedBody:
    "Tes 20 dernières soirées : rang, jeux, et les amis encore dans ta liste. Sans code salon, sans rejoin.",
  guestBody: "Connecte-toi avec un compte pour débloquer le carnet Signature.",
  seePacks: "Voir les forfaits",
  empty:
    "Pas encore de soirée archivée. Joue, puis quitte le salon - ça s’enregistre tout seul.",
  loadError: "Impossible de charger le carnet. Réessaie dans un instant.",
  missingRpc:
    "Le carnet n’est pas encore activé sur le serveur. Recolle le SQL feature-profile-04 (il finit par notify pgrst).",
  statsEvenings: "Soirées",
  statsEveningsEmoji: "🎉",
  statsGames: "Jeux joués",
  statsGamesEmoji: "🎮",
  statsWinrate: "Winrate",
  statsMvp: "MVP",
  statsMvpEmoji: "🏆",
  statsFavorite: "Jeu préféré",
  statsFavoriteEmoji: "⭐",
  favoriteNone: "—",
  shareCard: "Partager ma carte",
  sharePreviewTitle: "Ta carte",
  shareConfirm: "Partager",
  shareClose: "Fermer",
  shareGenerating: "Génération…",
  shareHint: "Instagram, WhatsApp… ou enregistre l’image.",
  shareError: "Impossible de créer la carte. Réessaie.",
  shareCropTitle: "Recadrer",
  shareCropHint: "Pince pour zoomer, glisse pour cadrer.",
  shareCropOk: "Valider",
  shareCropCancel: "Annuler",
  listTitle: "Tes 20 dernières soirées",
  chartScores: "Scores par soirée",
  chartRanks: "Rangs",
  chartRankFirst: "1er",
  chartRankSecond: "2e",
  chartRankRest: "3e+",
  shareDotsTitle: "Mes 20 dernières soirées",
};
